spring:
  application:
    name: timesheet

  datasource:
    url: jdbc:postgresql://localhost:5432/timesheet_db
    username: timesheet
    password: float123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
