spring:
  application:
    name: timesheet-rest
  datasource:
    url: jdbc:postgresql://localhost:5432/timesheet_db
    username: timesheet
    password: float123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true


server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true