spring:
  application:
    name: timesheet-page
server:
  port: ${PORT:0}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true